from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

def generate_pdf(filename, resume=None):
    file_path = f"{REPORT_DIR}/{filename}_report.pdf"
    c = canvas.Canvas(file_path, pagesize=letter)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, 750, "Resume Analysis Report")
    c.setFont("Helvetica", 11)
    c.drawString(50, 728, f"Resume: {filename}")

    y = 700
    if resume:
        c.drawString(50, y, f"AI Score: {resume.get('ai_score', 0)}%")
        y -= 18
        c.drawString(50, y, f"JD Match: {resume.get('jd_match_percent', 0)}%")
        y -= 24

        skills = resume.get("skills", [])
        if skills:
            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, "Top Skills")
            y -= 16
            c.setFont("Helvetica", 11)
            c.drawString(50, y, ", ".join(skills[:10]))
            y -= 24

        summary = resume.get("summary", {})
        if summary.get("summary"):
            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, "Summary")
            y -= 16
            c.setFont("Helvetica", 10)
            for line in summary["summary"].split("\n")[:4]:
                c.drawString(50, y, line[:90])
                y -= 14

    c.setFont("Helvetica", 10)
    c.drawString(50, 40, "Generated by Resume Analyzer Pro")
    c.save()
    return file_path
